version: '3.1'

services :
  db:
    image: postgres
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: kirill
      POSTGRES_PASSWORD: 1
      POSTGRES_DB: postgres
      POSTGRES_PORT: 5444
    volumes:
      - './pg_data:/var/lib/postgresql/data'
